name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  tests_for_django_playground:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: pip install tox-uv
      - name: Run lint
        run: | 
          cd django_playground
          tox run-parallel --skip-env format
